obj-y		+= qdsp6v2/
#liulinsheng@wind-mobi.com 20171023 begin
obj-$(CONFIG_WIND_ASUS_USB_TEMP_CHECK)  += usb_temp_check/
#liulinsheng@wind-mobi.com 20171023 end
# add by zhaozhensen@wind-mobi.com 20170110 begin
obj-$(CONFIG_WIND_ASUS_SIM_DEFAULT_CONFIG)  += sim_int_default_set/
# add by zhaozhensen@wind-mobi.com 20170110 end
obj-$(CONFIG_MSM_MCU_TIME_SYNC) += mcu_time_sync.o
