obj-y		+= qdsp6v2/
# add by zhaozhensen@wind-mobi.com 20170110 begin
obj-$(CONFIG_WIND_ASUS_SIM_DEFAULT_CONFIG)  += sim_int_default_set/
# add by zhaozhensen@wind-mobi.com 20170110 end
obj-$(CONFIG_MSM_MCU_TIME_SYNC) += mcu_time_sync.o
